// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrixmul_FLP_matrixmul_FLP_Pipeline_WC_L1_WC_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_C_TREADY,
        output_C_address0,
        output_C_ce0,
        output_C_q0,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TKEEP,
        out_C_TSTRB,
        out_C_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_C_TREADY;
output  [11:0] output_C_address0;
output   output_C_ce0;
input  [31:0] output_C_q0;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
output  [3:0] out_C_TKEEP;
output  [3:0] out_C_TSTRB;
output  [0:0] out_C_TLAST;

reg ap_idle;
reg output_C_ce0;
reg out_C_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_123_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_C_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln47_fu_153_p3;
reg   [5:0] select_ln47_reg_272;
reg   [5:0] select_ln47_reg_272_pp0_iter1_reg;
wire   [0:0] local_write_last_V_fu_199_p2;
reg   [0:0] local_write_last_V_reg_282;
reg   [0:0] local_write_last_V_reg_282_pp0_iter1_reg;
reg   [0:0] local_write_last_V_reg_282_pp0_iter2_reg;
reg   [0:0] local_write_last_V_reg_282_pp0_iter3_reg;
wire   [63:0] zext_ln51_2_fu_229_p1;
reg   [5:0] col_fu_62;
wire   [5:0] add_ln49_fu_205_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_col_load;
reg   [5:0] row_fu_66;
wire   [5:0] select_ln47_1_fu_161_p3;
reg   [5:0] ap_sig_allocacmp_row_load;
reg   [11:0] indvar_flatten71_fu_70;
wire   [11:0] add_ln47_1_fu_129_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten71_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln49_fu_147_p2;
wire   [5:0] add_ln47_fu_141_p2;
wire   [0:0] cmp69_mid1_fu_173_p2;
wire   [0:0] cmp69180_fu_179_p2;
wire   [0:0] select_ln47_2_fu_185_p3;
wire   [0:0] icmp_ln53_fu_193_p2;
wire   [11:0] grp_fu_238_p3;
wire   [5:0] grp_fu_238_p0;
wire   [5:0] grp_fu_238_p1;
wire   [5:0] grp_fu_238_p2;
reg    grp_fu_238_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_238_p00;
wire   [11:0] grp_fu_238_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_FLP_mac_muladd_6ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_6ns_6ns_12_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_238_p0),
    .din1(grp_fu_238_p1),
    .din2(grp_fu_238_p2),
    .ce(grp_fu_238_ce),
    .dout(grp_fu_238_p3)
);

matrixmul_FLP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_123_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_62 <= add_ln49_fu_205_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_62 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_123_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten71_fu_70 <= add_ln47_1_fu_129_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten71_fu_70 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_123_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            row_fu_66 <= select_ln47_1_fu_161_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_66 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        local_write_last_V_reg_282_pp0_iter1_reg <= local_write_last_V_reg_282;
        select_ln47_reg_272_pp0_iter1_reg <= select_ln47_reg_272;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        local_write_last_V_reg_282_pp0_iter2_reg <= local_write_last_V_reg_282_pp0_iter1_reg;
        local_write_last_V_reg_282_pp0_iter3_reg <= local_write_last_V_reg_282_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln47_fu_123_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_write_last_V_reg_282 <= local_write_last_V_fu_199_p2;
        select_ln47_reg_272 <= select_ln47_fu_153_p3;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_col_load = 6'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten71_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten71_load = indvar_flatten71_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_row_load = 6'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_238_ce = 1'b1;
    end else begin
        grp_fu_238_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_C_TDATA_blk_n = out_C_TREADY;
    end else begin
        out_C_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_C_TVALID = 1'b1;
    end else begin
        out_C_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        output_C_ce0 = 1'b1;
    end else begin
        output_C_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_1_fu_129_p2 = (ap_sig_allocacmp_indvar_flatten71_load + 12'd1);

assign add_ln47_fu_141_p2 = (ap_sig_allocacmp_row_load + 6'd1);

assign add_ln49_fu_205_p2 = (select_ln47_fu_153_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = (out_C_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp69180_fu_179_p2 = ((ap_sig_allocacmp_row_load == 6'd49) ? 1'b1 : 1'b0);

assign cmp69_mid1_fu_173_p2 = ((add_ln47_fu_141_p2 == 6'd49) ? 1'b1 : 1'b0);

assign grp_fu_238_p0 = grp_fu_238_p00;

assign grp_fu_238_p00 = select_ln47_1_fu_161_p3;

assign grp_fu_238_p1 = 12'd50;

assign grp_fu_238_p2 = grp_fu_238_p20;

assign grp_fu_238_p20 = select_ln47_reg_272_pp0_iter1_reg;

assign icmp_ln47_fu_123_p2 = ((ap_sig_allocacmp_indvar_flatten71_load == 12'd2500) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_147_p2 = ((ap_sig_allocacmp_col_load == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_193_p2 = ((select_ln47_fu_153_p3 == 6'd49) ? 1'b1 : 1'b0);

assign local_write_last_V_fu_199_p2 = (select_ln47_2_fu_185_p3 & icmp_ln53_fu_193_p2);

assign out_C_TDATA = output_C_q0;

assign out_C_TKEEP = 4'd15;

assign out_C_TLAST = local_write_last_V_reg_282_pp0_iter3_reg;

assign out_C_TSTRB = 4'd0;

assign output_C_address0 = zext_ln51_2_fu_229_p1;

assign select_ln47_1_fu_161_p3 = ((icmp_ln49_fu_147_p2[0:0] == 1'b1) ? add_ln47_fu_141_p2 : ap_sig_allocacmp_row_load);

assign select_ln47_2_fu_185_p3 = ((icmp_ln49_fu_147_p2[0:0] == 1'b1) ? cmp69_mid1_fu_173_p2 : cmp69180_fu_179_p2);

assign select_ln47_fu_153_p3 = ((icmp_ln49_fu_147_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_col_load);

assign zext_ln51_2_fu_229_p1 = grp_fu_238_p3;

endmodule //matrixmul_FLP_matrixmul_FLP_Pipeline_WC_L1_WC_L2
