// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrixmul_FXP_matrixmul_FXP_Pipeline_WC_L1_WC_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_C_TREADY,
        output_C_V_address0,
        output_C_V_ce0,
        output_C_V_q0,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TKEEP,
        out_C_TSTRB,
        out_C_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_C_TREADY;
output  [11:0] output_C_V_address0;
output   output_C_V_ce0;
input  [23:0] output_C_V_q0;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
output  [3:0] out_C_TKEEP;
output  [3:0] out_C_TSTRB;
output  [0:0] out_C_TLAST;

reg ap_idle;
reg output_C_V_ce0;
reg out_C_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_181_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_C_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln109_fu_211_p3;
reg   [5:0] select_ln109_reg_621;
reg   [5:0] select_ln109_reg_621_pp0_iter1_reg;
wire   [0:0] local_write_last_V_fu_257_p2;
reg   [0:0] local_write_last_V_reg_631;
reg   [0:0] local_write_last_V_reg_631_pp0_iter1_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter2_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter3_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter4_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter5_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter6_reg;
reg   [0:0] local_write_last_V_reg_631_pp0_iter7_reg;
reg   [23:0] p_Val2_s_reg_646;
reg   [0:0] p_Result_7_reg_653;
reg   [0:0] p_Result_7_reg_653_pp0_iter5_reg;
reg   [0:0] p_Result_7_reg_653_pp0_iter6_reg;
reg   [0:0] p_Result_7_reg_653_pp0_iter7_reg;
wire   [0:0] icmp_ln1136_fu_299_p2;
reg   [0:0] icmp_ln1136_reg_659;
reg   [0:0] icmp_ln1136_reg_659_pp0_iter6_reg;
reg   [0:0] icmp_ln1136_reg_659_pp0_iter7_reg;
wire   [23:0] tmp_V_2_fu_309_p3;
reg   [23:0] tmp_V_2_reg_664;
reg   [23:0] tmp_V_2_reg_664_pp0_iter6_reg;
wire   [31:0] sub_ln1145_fu_345_p2;
reg   [31:0] sub_ln1145_reg_671;
reg   [31:0] sub_ln1145_reg_671_pp0_iter6_reg;
wire   [23:0] trunc_ln1145_fu_351_p1;
reg   [23:0] trunc_ln1145_reg_678;
wire   [4:0] trunc_ln1148_fu_355_p1;
reg   [4:0] trunc_ln1148_reg_683;
wire   [7:0] trunc_ln1144_fu_359_p1;
reg   [7:0] trunc_ln1144_reg_688;
reg   [7:0] trunc_ln1144_reg_688_pp0_iter6_reg;
reg   [7:0] trunc_ln1144_reg_688_pp0_iter7_reg;
wire   [1:0] or_ln_fu_454_p3;
reg   [1:0] or_ln_reg_693;
wire   [0:0] icmp_ln1159_fu_462_p2;
reg   [0:0] icmp_ln1159_reg_698;
reg   [62:0] m_4_reg_703;
reg   [0:0] p_Result_5_reg_708;
wire   [63:0] zext_ln1136_2_fu_287_p1;
reg   [5:0] col_fu_120;
wire   [5:0] add_ln111_fu_263_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_col_load;
reg   [5:0] row_fu_124;
wire   [5:0] select_ln109_1_fu_219_p3;
reg   [5:0] ap_sig_allocacmp_row_load;
reg   [11:0] indvar_flatten71_fu_128;
wire   [11:0] add_ln109_1_fu_187_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten71_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln111_fu_205_p2;
wire   [5:0] add_ln109_fu_199_p2;
wire   [0:0] cmp109_mid1_fu_231_p2;
wire   [0:0] cmp109180_fu_237_p2;
wire   [0:0] select_ln109_2_fu_243_p3;
wire   [0:0] icmp_ln115_fu_251_p2;
wire   [11:0] grp_fu_587_p3;
wire   [23:0] tmp_V_fu_304_p2;
reg   [23:0] p_Result_s_fu_315_p4;
wire   [24:0] p_Result_8_fu_325_p3;
wire  signed [31:0] sext_ln1244_fu_333_p1;
reg   [31:0] l_fu_337_p3;
wire   [31:0] lsb_index_fu_363_p2;
wire   [30:0] tmp_fu_368_p4;
wire   [4:0] sub_ln1148_fu_384_p2;
wire   [23:0] zext_ln1148_fu_389_p1;
wire   [23:0] lshr_ln1148_fu_393_p2;
wire   [23:0] p_Result_4_fu_399_p2;
wire   [0:0] icmp_ln1147_fu_378_p2;
wire   [0:0] icmp_ln1148_fu_404_p2;
wire   [0:0] tmp_1_fu_416_p3;
wire   [23:0] add_ln1150_fu_430_p2;
wire   [0:0] p_Result_3_fu_435_p3;
wire   [0:0] xor_ln1150_fu_424_p2;
wire   [0:0] and_ln1150_fu_442_p2;
wire   [0:0] a_fu_410_p2;
wire   [0:0] or_ln1150_fu_448_p2;
wire   [31:0] add_ln1159_fu_471_p2;
wire   [63:0] zext_ln1158_fu_468_p1;
wire   [63:0] zext_ln1159_fu_476_p1;
wire   [31:0] sub_ln1160_fu_486_p2;
wire   [63:0] zext_ln1160_fu_491_p1;
wire   [63:0] lshr_ln1159_fu_480_p2;
wire   [63:0] shl_ln1160_fu_495_p2;
wire   [63:0] m_2_fu_501_p3;
wire   [63:0] zext_ln1162_fu_508_p1;
wire   [63:0] m_3_fu_511_p2;
wire   [7:0] sub_ln1165_fu_545_p2;
wire   [7:0] select_ln1144_fu_538_p3;
wire   [7:0] add_ln1170_fu_550_p2;
wire   [63:0] zext_ln1163_fu_535_p1;
wire   [8:0] tmp_7_fu_556_p3;
wire   [63:0] p_Result_9_fu_563_p5;
wire   [31:0] LD_fu_575_p1;
wire   [5:0] grp_fu_587_p0;
wire   [5:0] grp_fu_587_p1;
wire   [5:0] grp_fu_587_p2;
reg    grp_fu_587_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_587_p00;
wire   [11:0] grp_fu_587_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_FXP_mac_muladd_6ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_6ns_6ns_12_4_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_587_p0),
    .din1(grp_fu_587_p1),
    .din2(grp_fu_587_p2),
    .ce(grp_fu_587_ce),
    .dout(grp_fu_587_p3)
);

matrixmul_FXP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_120 <= add_ln111_fu_263_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_120 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten71_fu_128 <= add_ln109_1_fu_187_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten71_fu_128 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_181_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            row_fu_124 <= select_ln109_1_fu_219_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_124 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        local_write_last_V_reg_631_pp0_iter1_reg <= local_write_last_V_reg_631;
        select_ln109_reg_621_pp0_iter1_reg <= select_ln109_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln1136_reg_659 <= icmp_ln1136_fu_299_p2;
        icmp_ln1136_reg_659_pp0_iter6_reg <= icmp_ln1136_reg_659;
        icmp_ln1136_reg_659_pp0_iter7_reg <= icmp_ln1136_reg_659_pp0_iter6_reg;
        local_write_last_V_reg_631_pp0_iter2_reg <= local_write_last_V_reg_631_pp0_iter1_reg;
        local_write_last_V_reg_631_pp0_iter3_reg <= local_write_last_V_reg_631_pp0_iter2_reg;
        local_write_last_V_reg_631_pp0_iter4_reg <= local_write_last_V_reg_631_pp0_iter3_reg;
        local_write_last_V_reg_631_pp0_iter5_reg <= local_write_last_V_reg_631_pp0_iter4_reg;
        local_write_last_V_reg_631_pp0_iter6_reg <= local_write_last_V_reg_631_pp0_iter5_reg;
        local_write_last_V_reg_631_pp0_iter7_reg <= local_write_last_V_reg_631_pp0_iter6_reg;
        p_Result_7_reg_653 <= output_C_V_q0[32'd23];
        p_Result_7_reg_653_pp0_iter5_reg <= p_Result_7_reg_653;
        p_Result_7_reg_653_pp0_iter6_reg <= p_Result_7_reg_653_pp0_iter5_reg;
        p_Result_7_reg_653_pp0_iter7_reg <= p_Result_7_reg_653_pp0_iter6_reg;
        p_Val2_s_reg_646 <= output_C_V_q0;
        sub_ln1145_reg_671 <= sub_ln1145_fu_345_p2;
        sub_ln1145_reg_671_pp0_iter6_reg <= sub_ln1145_reg_671;
        tmp_V_2_reg_664 <= tmp_V_2_fu_309_p3;
        tmp_V_2_reg_664_pp0_iter6_reg <= tmp_V_2_reg_664;
        trunc_ln1144_reg_688 <= trunc_ln1144_fu_359_p1;
        trunc_ln1144_reg_688_pp0_iter6_reg <= trunc_ln1144_reg_688;
        trunc_ln1144_reg_688_pp0_iter7_reg <= trunc_ln1144_reg_688_pp0_iter6_reg;
        trunc_ln1145_reg_678 <= trunc_ln1145_fu_351_p1;
        trunc_ln1148_reg_683 <= trunc_ln1148_fu_355_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_659 == 1'd0))) begin
        icmp_ln1159_reg_698 <= icmp_ln1159_fu_462_p2;
        or_ln_reg_693[0] <= or_ln_fu_454_p3[0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_181_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_write_last_V_reg_631 <= local_write_last_V_fu_257_p2;
        select_ln109_reg_621 <= select_ln109_fu_211_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_659_pp0_iter6_reg == 1'd0))) begin
        m_4_reg_703 <= {{m_3_fu_511_p2[63:1]}};
        p_Result_5_reg_708 <= m_3_fu_511_p2[32'd25];
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_181_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_col_load = 6'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten71_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten71_load = indvar_flatten71_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_row_load = 6'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_587_ce = 1'b1;
    end else begin
        grp_fu_587_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        out_C_TDATA_blk_n = out_C_TREADY;
    end else begin
        out_C_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        out_C_TVALID = 1'b1;
    end else begin
        out_C_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        output_C_V_ce0 = 1'b1;
    end else begin
        output_C_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_575_p1 = p_Result_9_fu_563_p5[31:0];

assign a_fu_410_p2 = (icmp_ln1148_fu_404_p2 & icmp_ln1147_fu_378_p2);

assign add_ln109_1_fu_187_p2 = (ap_sig_allocacmp_indvar_flatten71_load + 12'd1);

assign add_ln109_fu_199_p2 = (ap_sig_allocacmp_row_load + 6'd1);

assign add_ln111_fu_263_p2 = (select_ln109_fu_211_p3 + 6'd1);

assign add_ln1150_fu_430_p2 = ($signed(trunc_ln1145_reg_678) + $signed(24'd16777192));

assign add_ln1159_fu_471_p2 = ($signed(sub_ln1145_reg_671_pp0_iter6_reg) + $signed(32'd4294967271));

assign add_ln1170_fu_550_p2 = (sub_ln1165_fu_545_p2 + select_ln1144_fu_538_p3);

assign and_ln1150_fu_442_p2 = (xor_ln1150_fu_424_p2 & p_Result_3_fu_435_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (out_C_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp109180_fu_237_p2 = ((ap_sig_allocacmp_row_load == 6'd49) ? 1'b1 : 1'b0);

assign cmp109_mid1_fu_231_p2 = ((add_ln109_fu_199_p2 == 6'd49) ? 1'b1 : 1'b0);

assign grp_fu_587_p0 = grp_fu_587_p00;

assign grp_fu_587_p00 = select_ln109_1_fu_219_p3;

assign grp_fu_587_p1 = 12'd50;

assign grp_fu_587_p2 = grp_fu_587_p20;

assign grp_fu_587_p20 = select_ln109_reg_621_pp0_iter1_reg;

assign icmp_ln109_fu_181_p2 = ((ap_sig_allocacmp_indvar_flatten71_load == 12'd2500) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_205_p2 = ((ap_sig_allocacmp_col_load == 6'd50) ? 1'b1 : 1'b0);

assign icmp_ln1136_fu_299_p2 = ((p_Val2_s_reg_646 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1147_fu_378_p2 = (($signed(tmp_fu_368_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1148_fu_404_p2 = ((p_Result_4_fu_399_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1159_fu_462_p2 = (($signed(lsb_index_fu_363_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_251_p2 = ((select_ln109_fu_211_p3 == 6'd49) ? 1'b1 : 1'b0);


always @ (sext_ln1244_fu_333_p1) begin
    if (sext_ln1244_fu_333_p1[0] == 1'b1) begin
        l_fu_337_p3 = 32'd0;
    end else if (sext_ln1244_fu_333_p1[1] == 1'b1) begin
        l_fu_337_p3 = 32'd1;
    end else if (sext_ln1244_fu_333_p1[2] == 1'b1) begin
        l_fu_337_p3 = 32'd2;
    end else if (sext_ln1244_fu_333_p1[3] == 1'b1) begin
        l_fu_337_p3 = 32'd3;
    end else if (sext_ln1244_fu_333_p1[4] == 1'b1) begin
        l_fu_337_p3 = 32'd4;
    end else if (sext_ln1244_fu_333_p1[5] == 1'b1) begin
        l_fu_337_p3 = 32'd5;
    end else if (sext_ln1244_fu_333_p1[6] == 1'b1) begin
        l_fu_337_p3 = 32'd6;
    end else if (sext_ln1244_fu_333_p1[7] == 1'b1) begin
        l_fu_337_p3 = 32'd7;
    end else if (sext_ln1244_fu_333_p1[8] == 1'b1) begin
        l_fu_337_p3 = 32'd8;
    end else if (sext_ln1244_fu_333_p1[9] == 1'b1) begin
        l_fu_337_p3 = 32'd9;
    end else if (sext_ln1244_fu_333_p1[10] == 1'b1) begin
        l_fu_337_p3 = 32'd10;
    end else if (sext_ln1244_fu_333_p1[11] == 1'b1) begin
        l_fu_337_p3 = 32'd11;
    end else if (sext_ln1244_fu_333_p1[12] == 1'b1) begin
        l_fu_337_p3 = 32'd12;
    end else if (sext_ln1244_fu_333_p1[13] == 1'b1) begin
        l_fu_337_p3 = 32'd13;
    end else if (sext_ln1244_fu_333_p1[14] == 1'b1) begin
        l_fu_337_p3 = 32'd14;
    end else if (sext_ln1244_fu_333_p1[15] == 1'b1) begin
        l_fu_337_p3 = 32'd15;
    end else if (sext_ln1244_fu_333_p1[16] == 1'b1) begin
        l_fu_337_p3 = 32'd16;
    end else if (sext_ln1244_fu_333_p1[17] == 1'b1) begin
        l_fu_337_p3 = 32'd17;
    end else if (sext_ln1244_fu_333_p1[18] == 1'b1) begin
        l_fu_337_p3 = 32'd18;
    end else if (sext_ln1244_fu_333_p1[19] == 1'b1) begin
        l_fu_337_p3 = 32'd19;
    end else if (sext_ln1244_fu_333_p1[20] == 1'b1) begin
        l_fu_337_p3 = 32'd20;
    end else if (sext_ln1244_fu_333_p1[21] == 1'b1) begin
        l_fu_337_p3 = 32'd21;
    end else if (sext_ln1244_fu_333_p1[22] == 1'b1) begin
        l_fu_337_p3 = 32'd22;
    end else if (sext_ln1244_fu_333_p1[23] == 1'b1) begin
        l_fu_337_p3 = 32'd23;
    end else if (sext_ln1244_fu_333_p1[24] == 1'b1) begin
        l_fu_337_p3 = 32'd24;
    end else if (sext_ln1244_fu_333_p1[25] == 1'b1) begin
        l_fu_337_p3 = 32'd25;
    end else if (sext_ln1244_fu_333_p1[26] == 1'b1) begin
        l_fu_337_p3 = 32'd26;
    end else if (sext_ln1244_fu_333_p1[27] == 1'b1) begin
        l_fu_337_p3 = 32'd27;
    end else if (sext_ln1244_fu_333_p1[28] == 1'b1) begin
        l_fu_337_p3 = 32'd28;
    end else if (sext_ln1244_fu_333_p1[29] == 1'b1) begin
        l_fu_337_p3 = 32'd29;
    end else if (sext_ln1244_fu_333_p1[30] == 1'b1) begin
        l_fu_337_p3 = 32'd30;
    end else if (sext_ln1244_fu_333_p1[31] == 1'b1) begin
        l_fu_337_p3 = 32'd31;
    end else begin
        l_fu_337_p3 = 32'd32;
    end
end

assign local_write_last_V_fu_257_p2 = (select_ln109_2_fu_243_p3 & icmp_ln115_fu_251_p2);

assign lsb_index_fu_363_p2 = ($signed(sub_ln1145_reg_671) + $signed(32'd4294967272));

assign lshr_ln1148_fu_393_p2 = 24'd16777215 >> zext_ln1148_fu_389_p1;

assign lshr_ln1159_fu_480_p2 = zext_ln1158_fu_468_p1 >> zext_ln1159_fu_476_p1;

assign m_2_fu_501_p3 = ((icmp_ln1159_reg_698[0:0] == 1'b1) ? lshr_ln1159_fu_480_p2 : shl_ln1160_fu_495_p2);

assign m_3_fu_511_p2 = (m_2_fu_501_p3 + zext_ln1162_fu_508_p1);

assign or_ln1150_fu_448_p2 = (and_ln1150_fu_442_p2 | a_fu_410_p2);

assign or_ln_fu_454_p3 = {{1'd0}, {or_ln1150_fu_448_p2}};

assign out_C_TDATA = ((icmp_ln1136_reg_659_pp0_iter7_reg[0:0] == 1'b1) ? 32'd0 : LD_fu_575_p1);

assign out_C_TKEEP = 4'd15;

assign out_C_TLAST = local_write_last_V_reg_631_pp0_iter7_reg;

assign out_C_TSTRB = 4'd0;

assign output_C_V_address0 = zext_ln1136_2_fu_287_p1;

assign p_Result_3_fu_435_p3 = tmp_V_2_reg_664[add_ln1150_fu_430_p2];

assign p_Result_4_fu_399_p2 = (tmp_V_2_reg_664 & lshr_ln1148_fu_393_p2);

assign p_Result_8_fu_325_p3 = {{1'd1}, {p_Result_s_fu_315_p4}};

assign p_Result_9_fu_563_p5 = {{zext_ln1163_fu_535_p1[63:32]}, {tmp_7_fu_556_p3}, {zext_ln1163_fu_535_p1[22:0]}};

integer ap_tvar_int_0;

always @ (tmp_V_2_fu_309_p3) begin
    for (ap_tvar_int_0 = 24 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 23 - 0) begin
            p_Result_s_fu_315_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_315_p4[ap_tvar_int_0] = tmp_V_2_fu_309_p3[23 - ap_tvar_int_0];
        end
    end
end

assign select_ln109_1_fu_219_p3 = ((icmp_ln111_fu_205_p2[0:0] == 1'b1) ? add_ln109_fu_199_p2 : ap_sig_allocacmp_row_load);

assign select_ln109_2_fu_243_p3 = ((icmp_ln111_fu_205_p2[0:0] == 1'b1) ? cmp109_mid1_fu_231_p2 : cmp109180_fu_237_p2);

assign select_ln109_fu_211_p3 = ((icmp_ln111_fu_205_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_col_load);

assign select_ln1144_fu_538_p3 = ((p_Result_5_reg_708[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign sext_ln1244_fu_333_p1 = $signed(p_Result_8_fu_325_p3);

assign shl_ln1160_fu_495_p2 = zext_ln1158_fu_468_p1 << zext_ln1160_fu_491_p1;

assign sub_ln1145_fu_345_p2 = (32'd24 - l_fu_337_p3);

assign sub_ln1148_fu_384_p2 = ($signed(5'd17) - $signed(trunc_ln1148_reg_683));

assign sub_ln1160_fu_486_p2 = (32'd25 - sub_ln1145_reg_671_pp0_iter6_reg);

assign sub_ln1165_fu_545_p2 = (8'd11 - trunc_ln1144_reg_688_pp0_iter7_reg);

assign tmp_1_fu_416_p3 = lsb_index_fu_363_p2[32'd31];

assign tmp_7_fu_556_p3 = {{p_Result_7_reg_653_pp0_iter7_reg}, {add_ln1170_fu_550_p2}};

assign tmp_V_2_fu_309_p3 = ((p_Result_7_reg_653[0:0] == 1'b1) ? tmp_V_fu_304_p2 : p_Val2_s_reg_646);

assign tmp_V_fu_304_p2 = (24'd0 - p_Val2_s_reg_646);

assign tmp_fu_368_p4 = {{lsb_index_fu_363_p2[31:1]}};

assign trunc_ln1144_fu_359_p1 = l_fu_337_p3[7:0];

assign trunc_ln1145_fu_351_p1 = sub_ln1145_fu_345_p2[23:0];

assign trunc_ln1148_fu_355_p1 = sub_ln1145_fu_345_p2[4:0];

assign xor_ln1150_fu_424_p2 = (tmp_1_fu_416_p3 ^ 1'd1);

assign zext_ln1136_2_fu_287_p1 = grp_fu_587_p3;

assign zext_ln1148_fu_389_p1 = sub_ln1148_fu_384_p2;

assign zext_ln1158_fu_468_p1 = tmp_V_2_reg_664_pp0_iter6_reg;

assign zext_ln1159_fu_476_p1 = add_ln1159_fu_471_p2;

assign zext_ln1160_fu_491_p1 = sub_ln1160_fu_486_p2;

assign zext_ln1162_fu_508_p1 = or_ln_reg_693;

assign zext_ln1163_fu_535_p1 = m_4_reg_703;

always @ (posedge ap_clk) begin
    or_ln_reg_693[1] <= 1'b0;
end

endmodule //matrixmul_FXP_matrixmul_FXP_Pipeline_WC_L1_WC_L2
