// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrixmul_FXP_matrixmul_FXP_Pipeline_RA_L1_RA_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_AB_TVALID,
        input_A_V_address0,
        input_A_V_ce0,
        input_A_V_we0,
        input_A_V_d0,
        in_AB_TDATA,
        in_AB_TREADY,
        in_AB_TKEEP,
        in_AB_TSTRB,
        in_AB_TLAST,
        grp_fu_108_p_din0,
        grp_fu_108_p_dout0,
        grp_fu_108_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_AB_TVALID;
output  [11:0] input_A_V_address0;
output   input_A_V_ce0;
output   input_A_V_we0;
output  [23:0] input_A_V_d0;
input  [31:0] in_AB_TDATA;
output   in_AB_TREADY;
input  [3:0] in_AB_TKEEP;
input  [3:0] in_AB_TSTRB;
input  [0:0] in_AB_TLAST;
output  [31:0] grp_fu_108_p_din0;
input  [63:0] grp_fu_108_p_dout0;
output   grp_fu_108_p_ce;

reg ap_idle;
reg input_A_V_ce0;
reg input_A_V_we0;
reg in_AB_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln78_fu_150_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_AB_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_0_reg_487;
reg   [31:0] p_0_reg_487_pp0_iter1_reg;
reg   [31:0] p_0_reg_487_pp0_iter2_reg;
reg   [31:0] p_0_reg_487_pp0_iter3_reg;
wire   [31:0] tmp_4_fu_166_p1;
reg   [0:0] p_Result_s_reg_497;
reg   [10:0] exp_tmp_reg_502;
wire   [51:0] trunc_ln600_fu_202_p1;
reg   [51:0] trunc_ln600_reg_507;
wire   [0:0] icmp_ln606_fu_206_p2;
reg   [0:0] icmp_ln606_reg_512;
reg   [0:0] icmp_ln606_reg_512_pp0_iter2_reg;
reg   [0:0] icmp_ln606_reg_512_pp0_iter3_reg;
wire   [5:0] select_ln78_fu_230_p3;
reg   [5:0] select_ln78_reg_519;
reg   [5:0] select_ln78_reg_519_pp0_iter3_reg;
wire   [53:0] man_V_4_fu_270_p3;
reg   [53:0] man_V_4_reg_529;
reg   [53:0] man_V_4_reg_529_pp0_iter3_reg;
wire  signed [11:0] sh_amt_fu_301_p3;
reg  signed [11:0] sh_amt_reg_534;
wire   [0:0] icmp_ln617_fu_309_p2;
reg   [0:0] icmp_ln617_reg_541;
wire   [23:0] trunc_ln618_fu_315_p1;
reg   [23:0] trunc_ln618_reg_546;
wire   [0:0] and_ln616_fu_330_p2;
reg   [0:0] and_ln616_reg_552;
reg   [0:0] and_ln616_reg_552_pp0_iter3_reg;
wire  signed [31:0] sext_ln616_fu_352_p1;
reg  signed [31:0] sext_ln616_reg_557;
wire   [0:0] icmp_ln620_fu_355_p2;
reg   [0:0] icmp_ln620_reg_562;
wire   [23:0] select_ln617_fu_392_p3;
reg   [23:0] select_ln617_reg_567;
wire   [23:0] select_ln606_fu_442_p3;
reg   [23:0] select_ln606_reg_577;
wire   [63:0] zext_ln83_2_fu_449_p1;
reg   [5:0] col_fu_92;
wire   [5:0] add_ln80_fu_336_p2;
wire    ap_loop_init;
reg   [5:0] row_fu_96;
wire   [5:0] select_ln78_1_fu_238_p3;
reg   [11:0] indvar_flatten_fu_100;
wire   [11:0] add_ln78_1_fu_156_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [63:0] ireg_fu_176_p1;
wire   [62:0] trunc_ln590_fu_180_p1;
wire   [0:0] icmp_ln80_fu_224_p2;
wire   [5:0] add_ln78_fu_218_p2;
wire   [52:0] p_Result_11_fu_253_p3;
wire   [53:0] zext_ln604_fu_260_p1;
wire   [53:0] man_V_3_fu_264_p2;
wire   [11:0] zext_ln501_fu_250_p1;
wire   [11:0] F2_fu_277_p2;
wire   [0:0] icmp_ln616_fu_283_p2;
wire   [11:0] add_ln616_fu_289_p2;
wire   [11:0] sub_ln616_fu_295_p2;
wire   [0:0] or_ln617_fu_319_p2;
wire   [0:0] xor_ln617_fu_324_p2;
wire   [23:0] sext_ln616cast_fu_365_p1;
wire   [0:0] icmp_ln638_fu_360_p2;
wire   [23:0] shl_ln639_fu_369_p2;
wire   [0:0] xor_ln606_fu_382_p2;
wire   [0:0] and_ln617_fu_387_p2;
wire   [23:0] select_ln638_fu_374_p3;
wire   [53:0] zext_ln621_fu_402_p1;
wire   [53:0] ashr_ln621_fu_405_p2;
wire   [0:0] tmp_fu_414_p3;
wire   [23:0] trunc_ln621_fu_410_p1;
wire   [23:0] select_ln623_fu_421_p3;
wire   [23:0] select_ln620_fu_429_p3;
wire   [23:0] select_ln616_fu_436_p3;
wire   [11:0] grp_fu_453_p3;
wire   [5:0] grp_fu_453_p0;
wire   [5:0] grp_fu_453_p1;
wire   [5:0] grp_fu_453_p2;
reg    grp_fu_129_ce;
reg    grp_fu_453_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_453_p00;
wire   [11:0] grp_fu_453_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_FXP_mac_muladd_6ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_6ns_6ns_12_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_453_p0),
    .din1(grp_fu_453_p1),
    .din2(grp_fu_453_p2),
    .ce(grp_fu_453_ce),
    .dout(grp_fu_453_p3)
);

matrixmul_FXP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            col_fu_92 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            col_fu_92 <= add_ln80_fu_336_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln78_fu_150_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            indvar_flatten_fu_100 <= add_ln78_1_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_100 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            row_fu_96 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            row_fu_96 <= select_ln78_1_fu_238_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_512 == 1'd0))) begin
        and_ln616_reg_552 <= and_ln616_fu_330_p2;
        icmp_ln617_reg_541 <= icmp_ln617_fu_309_p2;
        man_V_4_reg_529 <= man_V_4_fu_270_p3;
        sh_amt_reg_534 <= sh_amt_fu_301_p3;
        trunc_ln618_reg_546 <= trunc_ln618_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln616_reg_552_pp0_iter3_reg <= and_ln616_reg_552;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln606_reg_512_pp0_iter2_reg <= icmp_ln606_reg_512;
        icmp_ln606_reg_512_pp0_iter3_reg <= icmp_ln606_reg_512_pp0_iter2_reg;
        man_V_4_reg_529_pp0_iter3_reg <= man_V_4_reg_529;
        p_0_reg_487_pp0_iter2_reg <= p_0_reg_487_pp0_iter1_reg;
        p_0_reg_487_pp0_iter3_reg <= p_0_reg_487_pp0_iter2_reg;
        select_ln606_reg_577 <= select_ln606_fu_442_p3;
        select_ln78_reg_519 <= select_ln78_fu_230_p3;
        select_ln78_reg_519_pp0_iter3_reg <= select_ln78_reg_519;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        exp_tmp_reg_502 <= {{ireg_fu_176_p1[62:52]}};
        icmp_ln606_reg_512 <= icmp_ln606_fu_206_p2;
        p_0_reg_487_pp0_iter1_reg <= p_0_reg_487;
        p_Result_s_reg_497 <= ireg_fu_176_p1[32'd63];
        trunc_ln600_reg_507 <= trunc_ln600_fu_202_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln616_reg_552) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_512_pp0_iter2_reg == 1'd0))) begin
        icmp_ln620_reg_562 <= icmp_ln620_fu_355_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln78_fu_150_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_reg_487 <= in_AB_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln616_reg_552) & (icmp_ln606_reg_512_pp0_iter2_reg == 1'd0))) begin
        select_ln617_reg_567 <= select_ln617_fu_392_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_512_pp0_iter2_reg == 1'd0))) begin
        sext_ln616_reg_557 <= sext_ln616_fu_352_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln78_fu_150_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_129_ce = 1'b1;
    end else begin
        grp_fu_129_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_453_ce = 1'b1;
    end else begin
        grp_fu_453_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln78_fu_150_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_AB_TDATA_blk_n = in_AB_TVALID;
    end else begin
        in_AB_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln78_fu_150_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_AB_TREADY = 1'b1;
    end else begin
        in_AB_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        input_A_V_ce0 = 1'b1;
    end else begin
        input_A_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        input_A_V_we0 = 1'b1;
    end else begin
        input_A_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_277_p2 = (12'd1075 - zext_ln501_fu_250_p1);

assign add_ln616_fu_289_p2 = ($signed(F2_fu_277_p2) + $signed(12'd4083));

assign add_ln78_1_fu_156_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln78_fu_218_p2 = (row_fu_96 + 6'd1);

assign add_ln80_fu_336_p2 = (select_ln78_fu_230_p3 + 6'd1);

assign and_ln616_fu_330_p2 = (xor_ln617_fu_324_p2 & icmp_ln616_fu_283_p2);

assign and_ln617_fu_387_p2 = (xor_ln606_fu_382_p2 & icmp_ln617_reg_541);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln78_fu_150_p2 == 1'd0) & (in_AB_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln78_fu_150_p2 == 1'd0) & (in_AB_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln78_fu_150_p2 == 1'd0) & (in_AB_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ashr_ln621_fu_405_p2 = $signed(man_V_4_reg_529_pp0_iter3_reg) >>> zext_ln621_fu_402_p1;

assign grp_fu_108_p_ce = grp_fu_129_ce;

assign grp_fu_108_p_din0 = tmp_4_fu_166_p1;

assign grp_fu_453_p0 = grp_fu_453_p00;

assign grp_fu_453_p00 = select_ln78_1_fu_238_p3;

assign grp_fu_453_p1 = 12'd50;

assign grp_fu_453_p2 = grp_fu_453_p20;

assign grp_fu_453_p20 = select_ln78_reg_519_pp0_iter3_reg;

assign icmp_ln606_fu_206_p2 = ((trunc_ln590_fu_180_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln616_fu_283_p2 = (($signed(F2_fu_277_p2) > $signed(12'd13)) ? 1'b1 : 1'b0);

assign icmp_ln617_fu_309_p2 = ((F2_fu_277_p2 == 12'd13) ? 1'b1 : 1'b0);

assign icmp_ln620_fu_355_p2 = ((sh_amt_reg_534 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln638_fu_360_p2 = ((sh_amt_reg_534 < 12'd24) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_150_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2500) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_224_p2 = ((col_fu_92 == 6'd50) ? 1'b1 : 1'b0);

assign input_A_V_address0 = zext_ln83_2_fu_449_p1;

assign input_A_V_d0 = select_ln606_reg_577;

assign ireg_fu_176_p1 = grp_fu_108_p_dout0;

assign man_V_3_fu_264_p2 = (54'd0 - zext_ln604_fu_260_p1);

assign man_V_4_fu_270_p3 = ((p_Result_s_reg_497[0:0] == 1'b1) ? man_V_3_fu_264_p2 : zext_ln604_fu_260_p1);

assign or_ln617_fu_319_p2 = (icmp_ln617_fu_309_p2 | icmp_ln606_reg_512);

assign p_Result_11_fu_253_p3 = {{1'd1}, {trunc_ln600_reg_507}};

assign select_ln606_fu_442_p3 = ((icmp_ln606_reg_512_pp0_iter3_reg[0:0] == 1'b1) ? 24'd0 : select_ln616_fu_436_p3);

assign select_ln616_fu_436_p3 = ((and_ln616_reg_552_pp0_iter3_reg[0:0] == 1'b1) ? select_ln620_fu_429_p3 : select_ln617_reg_567);

assign select_ln617_fu_392_p3 = ((and_ln617_fu_387_p2[0:0] == 1'b1) ? trunc_ln618_reg_546 : select_ln638_fu_374_p3);

assign select_ln620_fu_429_p3 = ((icmp_ln620_reg_562[0:0] == 1'b1) ? trunc_ln621_fu_410_p1 : select_ln623_fu_421_p3);

assign select_ln623_fu_421_p3 = ((tmp_fu_414_p3[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln638_fu_374_p3 = ((icmp_ln638_fu_360_p2[0:0] == 1'b1) ? shl_ln639_fu_369_p2 : 24'd0);

assign select_ln78_1_fu_238_p3 = ((icmp_ln80_fu_224_p2[0:0] == 1'b1) ? add_ln78_fu_218_p2 : row_fu_96);

assign select_ln78_fu_230_p3 = ((icmp_ln80_fu_224_p2[0:0] == 1'b1) ? 6'd0 : col_fu_92);

assign sext_ln616_fu_352_p1 = sh_amt_reg_534;

assign sext_ln616cast_fu_365_p1 = sext_ln616_fu_352_p1[23:0];

assign sh_amt_fu_301_p3 = ((icmp_ln616_fu_283_p2[0:0] == 1'b1) ? add_ln616_fu_289_p2 : sub_ln616_fu_295_p2);

assign shl_ln639_fu_369_p2 = trunc_ln618_reg_546 << sext_ln616cast_fu_365_p1;

assign sub_ln616_fu_295_p2 = (12'd13 - F2_fu_277_p2);

assign tmp_4_fu_166_p1 = in_AB_TDATA;

assign tmp_fu_414_p3 = p_0_reg_487_pp0_iter3_reg[32'd31];

assign trunc_ln590_fu_180_p1 = ireg_fu_176_p1[62:0];

assign trunc_ln600_fu_202_p1 = ireg_fu_176_p1[51:0];

assign trunc_ln618_fu_315_p1 = man_V_4_fu_270_p3[23:0];

assign trunc_ln621_fu_410_p1 = ashr_ln621_fu_405_p2[23:0];

assign xor_ln606_fu_382_p2 = (icmp_ln606_reg_512_pp0_iter2_reg ^ 1'd1);

assign xor_ln617_fu_324_p2 = (or_ln617_fu_319_p2 ^ 1'd1);

assign zext_ln501_fu_250_p1 = exp_tmp_reg_502;

assign zext_ln604_fu_260_p1 = p_Result_11_fu_253_p3;

assign zext_ln621_fu_402_p1 = $unsigned(sext_ln616_reg_557);

assign zext_ln83_2_fu_449_p1 = grp_fu_453_p3;

endmodule //matrixmul_FXP_matrixmul_FXP_Pipeline_RA_L1_RA_L2
