// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrixmul_FXP_matrixmul_FXP_Pipeline_WC_L1_WC_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_C_TREADY,
        output_C_V_address0,
        output_C_V_ce0,
        output_C_V_q0,
        out_C_TDATA,
        out_C_TVALID,
        out_C_TKEEP,
        out_C_TSTRB,
        out_C_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_C_TREADY;
output  [8:0] output_C_V_address0;
output   output_C_V_ce0;
input  [23:0] output_C_V_q0;
output  [31:0] out_C_TDATA;
output   out_C_TVALID;
output  [3:0] out_C_TKEEP;
output  [3:0] out_C_TSTRB;
output  [0:0] out_C_TLAST;

reg ap_idle;
reg output_C_V_ce0;
reg out_C_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_C_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] add_ln1136_1_fu_283_p2;
reg   [8:0] add_ln1136_1_reg_647;
wire   [0:0] local_write_last_V_fu_295_p2;
reg   [0:0] local_write_last_V_reg_652;
reg   [0:0] local_write_last_V_reg_652_pp0_iter1_reg;
reg   [0:0] local_write_last_V_reg_652_pp0_iter2_reg;
reg   [0:0] local_write_last_V_reg_652_pp0_iter3_reg;
reg   [0:0] local_write_last_V_reg_652_pp0_iter4_reg;
reg   [0:0] local_write_last_V_reg_652_pp0_iter5_reg;
reg   [23:0] p_Val2_s_reg_662;
reg   [0:0] p_Result_7_reg_669;
reg   [0:0] p_Result_7_reg_669_pp0_iter3_reg;
reg   [0:0] p_Result_7_reg_669_pp0_iter4_reg;
reg   [0:0] p_Result_7_reg_669_pp0_iter5_reg;
wire   [0:0] icmp_ln1136_fu_334_p2;
reg   [0:0] icmp_ln1136_reg_675;
reg   [0:0] icmp_ln1136_reg_675_pp0_iter4_reg;
reg   [0:0] icmp_ln1136_reg_675_pp0_iter5_reg;
wire   [23:0] tmp_V_2_fu_344_p3;
reg   [23:0] tmp_V_2_reg_680;
reg   [23:0] tmp_V_2_reg_680_pp0_iter4_reg;
wire   [31:0] sub_ln1145_fu_380_p2;
reg   [31:0] sub_ln1145_reg_687;
reg   [31:0] sub_ln1145_reg_687_pp0_iter4_reg;
wire   [23:0] trunc_ln1145_fu_386_p1;
reg   [23:0] trunc_ln1145_reg_694;
wire   [4:0] trunc_ln1148_fu_390_p1;
reg   [4:0] trunc_ln1148_reg_699;
wire   [7:0] trunc_ln1144_fu_394_p1;
reg   [7:0] trunc_ln1144_reg_704;
reg   [7:0] trunc_ln1144_reg_704_pp0_iter4_reg;
reg   [7:0] trunc_ln1144_reg_704_pp0_iter5_reg;
wire   [1:0] or_ln_fu_489_p3;
reg   [1:0] or_ln_reg_709;
wire   [0:0] icmp_ln1159_fu_497_p2;
reg   [0:0] icmp_ln1159_reg_714;
reg   [62:0] m_4_reg_719;
reg   [0:0] p_Result_5_reg_724;
wire   [63:0] zext_ln1136_2_fu_322_p1;
reg   [4:0] col_fu_126;
wire   [4:0] add_ln111_fu_301_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_col_load;
reg   [4:0] row_fu_130;
wire   [4:0] select_ln109_1_fu_225_p3;
reg   [4:0] ap_sig_allocacmp_row_load;
reg   [8:0] indvar_flatten41_fu_134;
wire   [8:0] add_ln109_1_fu_193_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten41_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln111_fu_211_p2;
wire   [4:0] add_ln109_fu_205_p2;
wire   [6:0] tmp_1_fu_241_p3;
wire   [8:0] tmp_s_fu_233_p3;
wire   [8:0] zext_ln1136_fu_249_p1;
wire   [0:0] cmp109_mid1_fu_259_p2;
wire   [0:0] cmp109101_fu_265_p2;
wire   [4:0] select_ln109_fu_217_p3;
wire   [8:0] add_ln1136_fu_253_p2;
wire   [8:0] zext_ln1136_1_fu_279_p1;
wire   [0:0] select_ln109_2_fu_271_p3;
wire   [0:0] icmp_ln115_fu_289_p2;
wire   [23:0] tmp_V_fu_339_p2;
reg   [23:0] p_Result_s_fu_350_p4;
wire   [24:0] p_Result_8_fu_360_p3;
wire  signed [31:0] sext_ln1244_fu_368_p1;
reg   [31:0] l_fu_372_p3;
wire   [31:0] lsb_index_fu_398_p2;
wire   [30:0] tmp_fu_403_p4;
wire   [4:0] sub_ln1148_fu_419_p2;
wire   [23:0] zext_ln1148_fu_424_p1;
wire   [23:0] lshr_ln1148_fu_428_p2;
wire   [23:0] p_Result_4_fu_434_p2;
wire   [0:0] icmp_ln1147_fu_413_p2;
wire   [0:0] icmp_ln1148_fu_439_p2;
wire   [0:0] tmp_2_fu_451_p3;
wire   [23:0] add_ln1150_fu_465_p2;
wire   [0:0] p_Result_3_fu_470_p3;
wire   [0:0] xor_ln1150_fu_459_p2;
wire   [0:0] and_ln1150_fu_477_p2;
wire   [0:0] a_fu_445_p2;
wire   [0:0] or_ln1150_fu_483_p2;
wire   [31:0] add_ln1159_fu_506_p2;
wire   [63:0] zext_ln1158_fu_503_p1;
wire   [63:0] zext_ln1159_fu_511_p1;
wire   [31:0] sub_ln1160_fu_521_p2;
wire   [63:0] zext_ln1160_fu_526_p1;
wire   [63:0] lshr_ln1159_fu_515_p2;
wire   [63:0] shl_ln1160_fu_530_p2;
wire   [63:0] m_2_fu_536_p3;
wire   [63:0] zext_ln1162_fu_543_p1;
wire   [63:0] m_3_fu_546_p2;
wire   [7:0] sub_ln1165_fu_580_p2;
wire   [7:0] select_ln1144_fu_573_p3;
wire   [7:0] add_ln1170_fu_585_p2;
wire   [63:0] zext_ln1163_fu_570_p1;
wire   [8:0] tmp_7_fu_591_p3;
wire   [63:0] p_Result_9_fu_598_p5;
wire   [31:0] LD_fu_610_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_FXP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            col_fu_126 <= add_ln111_fu_301_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_126 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten41_fu_134 <= add_ln109_1_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_134 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            row_fu_130 <= select_ln109_1_fu_225_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            row_fu_130 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_187_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln1136_1_reg_647 <= add_ln1136_1_fu_283_p2;
        local_write_last_V_reg_652 <= local_write_last_V_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        local_write_last_V_reg_652_pp0_iter1_reg <= local_write_last_V_reg_652;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln1136_reg_675 <= icmp_ln1136_fu_334_p2;
        icmp_ln1136_reg_675_pp0_iter4_reg <= icmp_ln1136_reg_675;
        icmp_ln1136_reg_675_pp0_iter5_reg <= icmp_ln1136_reg_675_pp0_iter4_reg;
        local_write_last_V_reg_652_pp0_iter2_reg <= local_write_last_V_reg_652_pp0_iter1_reg;
        local_write_last_V_reg_652_pp0_iter3_reg <= local_write_last_V_reg_652_pp0_iter2_reg;
        local_write_last_V_reg_652_pp0_iter4_reg <= local_write_last_V_reg_652_pp0_iter3_reg;
        local_write_last_V_reg_652_pp0_iter5_reg <= local_write_last_V_reg_652_pp0_iter4_reg;
        p_Result_7_reg_669 <= output_C_V_q0[32'd23];
        p_Result_7_reg_669_pp0_iter3_reg <= p_Result_7_reg_669;
        p_Result_7_reg_669_pp0_iter4_reg <= p_Result_7_reg_669_pp0_iter3_reg;
        p_Result_7_reg_669_pp0_iter5_reg <= p_Result_7_reg_669_pp0_iter4_reg;
        p_Val2_s_reg_662 <= output_C_V_q0;
        sub_ln1145_reg_687 <= sub_ln1145_fu_380_p2;
        sub_ln1145_reg_687_pp0_iter4_reg <= sub_ln1145_reg_687;
        tmp_V_2_reg_680 <= tmp_V_2_fu_344_p3;
        tmp_V_2_reg_680_pp0_iter4_reg <= tmp_V_2_reg_680;
        trunc_ln1144_reg_704 <= trunc_ln1144_fu_394_p1;
        trunc_ln1144_reg_704_pp0_iter4_reg <= trunc_ln1144_reg_704;
        trunc_ln1144_reg_704_pp0_iter5_reg <= trunc_ln1144_reg_704_pp0_iter4_reg;
        trunc_ln1145_reg_694 <= trunc_ln1145_fu_386_p1;
        trunc_ln1148_reg_699 <= trunc_ln1148_fu_390_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_675 == 1'd0))) begin
        icmp_ln1159_reg_714 <= icmp_ln1159_fu_497_p2;
        or_ln_reg_709[0] <= or_ln_fu_489_p3[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1136_reg_675_pp0_iter4_reg == 1'd0))) begin
        m_4_reg_719 <= {{m_3_fu_546_p2[63:1]}};
        p_Result_5_reg_724 <= m_3_fu_546_p2[32'd25];
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_col_load = 5'd0;
    end else begin
        ap_sig_allocacmp_col_load = col_fu_126;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_row_load = 5'd0;
    end else begin
        ap_sig_allocacmp_row_load = row_fu_130;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        out_C_TDATA_blk_n = out_C_TREADY;
    end else begin
        out_C_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        out_C_TVALID = 1'b1;
    end else begin
        out_C_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_C_V_ce0 = 1'b1;
    end else begin
        output_C_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LD_fu_610_p1 = p_Result_9_fu_598_p5[31:0];

assign a_fu_445_p2 = (icmp_ln1148_fu_439_p2 & icmp_ln1147_fu_413_p2);

assign add_ln109_1_fu_193_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 9'd1);

assign add_ln109_fu_205_p2 = (ap_sig_allocacmp_row_load + 5'd1);

assign add_ln111_fu_301_p2 = (select_ln109_fu_217_p3 + 5'd1);

assign add_ln1136_1_fu_283_p2 = (add_ln1136_fu_253_p2 + zext_ln1136_1_fu_279_p1);

assign add_ln1136_fu_253_p2 = (tmp_s_fu_233_p3 + zext_ln1136_fu_249_p1);

assign add_ln1150_fu_465_p2 = ($signed(trunc_ln1145_reg_694) + $signed(24'd16777192));

assign add_ln1159_fu_506_p2 = ($signed(sub_ln1145_reg_687_pp0_iter4_reg) + $signed(32'd4294967271));

assign add_ln1170_fu_585_p2 = (sub_ln1165_fu_580_p2 + select_ln1144_fu_573_p3);

assign and_ln1150_fu_477_p2 = (xor_ln1150_fu_459_p2 & p_Result_3_fu_470_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_C_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = (out_C_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp109101_fu_265_p2 = ((ap_sig_allocacmp_row_load == 5'd19) ? 1'b1 : 1'b0);

assign cmp109_mid1_fu_259_p2 = ((add_ln109_fu_205_p2 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_187_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_211_p2 = ((ap_sig_allocacmp_col_load == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln1136_fu_334_p2 = ((p_Val2_s_reg_662 == 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1147_fu_413_p2 = (($signed(tmp_fu_403_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1148_fu_439_p2 = ((p_Result_4_fu_434_p2 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln1159_fu_497_p2 = (($signed(lsb_index_fu_398_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_289_p2 = ((select_ln109_fu_217_p3 == 5'd19) ? 1'b1 : 1'b0);


always @ (sext_ln1244_fu_368_p1) begin
    if (sext_ln1244_fu_368_p1[0] == 1'b1) begin
        l_fu_372_p3 = 32'd0;
    end else if (sext_ln1244_fu_368_p1[1] == 1'b1) begin
        l_fu_372_p3 = 32'd1;
    end else if (sext_ln1244_fu_368_p1[2] == 1'b1) begin
        l_fu_372_p3 = 32'd2;
    end else if (sext_ln1244_fu_368_p1[3] == 1'b1) begin
        l_fu_372_p3 = 32'd3;
    end else if (sext_ln1244_fu_368_p1[4] == 1'b1) begin
        l_fu_372_p3 = 32'd4;
    end else if (sext_ln1244_fu_368_p1[5] == 1'b1) begin
        l_fu_372_p3 = 32'd5;
    end else if (sext_ln1244_fu_368_p1[6] == 1'b1) begin
        l_fu_372_p3 = 32'd6;
    end else if (sext_ln1244_fu_368_p1[7] == 1'b1) begin
        l_fu_372_p3 = 32'd7;
    end else if (sext_ln1244_fu_368_p1[8] == 1'b1) begin
        l_fu_372_p3 = 32'd8;
    end else if (sext_ln1244_fu_368_p1[9] == 1'b1) begin
        l_fu_372_p3 = 32'd9;
    end else if (sext_ln1244_fu_368_p1[10] == 1'b1) begin
        l_fu_372_p3 = 32'd10;
    end else if (sext_ln1244_fu_368_p1[11] == 1'b1) begin
        l_fu_372_p3 = 32'd11;
    end else if (sext_ln1244_fu_368_p1[12] == 1'b1) begin
        l_fu_372_p3 = 32'd12;
    end else if (sext_ln1244_fu_368_p1[13] == 1'b1) begin
        l_fu_372_p3 = 32'd13;
    end else if (sext_ln1244_fu_368_p1[14] == 1'b1) begin
        l_fu_372_p3 = 32'd14;
    end else if (sext_ln1244_fu_368_p1[15] == 1'b1) begin
        l_fu_372_p3 = 32'd15;
    end else if (sext_ln1244_fu_368_p1[16] == 1'b1) begin
        l_fu_372_p3 = 32'd16;
    end else if (sext_ln1244_fu_368_p1[17] == 1'b1) begin
        l_fu_372_p3 = 32'd17;
    end else if (sext_ln1244_fu_368_p1[18] == 1'b1) begin
        l_fu_372_p3 = 32'd18;
    end else if (sext_ln1244_fu_368_p1[19] == 1'b1) begin
        l_fu_372_p3 = 32'd19;
    end else if (sext_ln1244_fu_368_p1[20] == 1'b1) begin
        l_fu_372_p3 = 32'd20;
    end else if (sext_ln1244_fu_368_p1[21] == 1'b1) begin
        l_fu_372_p3 = 32'd21;
    end else if (sext_ln1244_fu_368_p1[22] == 1'b1) begin
        l_fu_372_p3 = 32'd22;
    end else if (sext_ln1244_fu_368_p1[23] == 1'b1) begin
        l_fu_372_p3 = 32'd23;
    end else if (sext_ln1244_fu_368_p1[24] == 1'b1) begin
        l_fu_372_p3 = 32'd24;
    end else if (sext_ln1244_fu_368_p1[25] == 1'b1) begin
        l_fu_372_p3 = 32'd25;
    end else if (sext_ln1244_fu_368_p1[26] == 1'b1) begin
        l_fu_372_p3 = 32'd26;
    end else if (sext_ln1244_fu_368_p1[27] == 1'b1) begin
        l_fu_372_p3 = 32'd27;
    end else if (sext_ln1244_fu_368_p1[28] == 1'b1) begin
        l_fu_372_p3 = 32'd28;
    end else if (sext_ln1244_fu_368_p1[29] == 1'b1) begin
        l_fu_372_p3 = 32'd29;
    end else if (sext_ln1244_fu_368_p1[30] == 1'b1) begin
        l_fu_372_p3 = 32'd30;
    end else if (sext_ln1244_fu_368_p1[31] == 1'b1) begin
        l_fu_372_p3 = 32'd31;
    end else begin
        l_fu_372_p3 = 32'd32;
    end
end

assign local_write_last_V_fu_295_p2 = (select_ln109_2_fu_271_p3 & icmp_ln115_fu_289_p2);

assign lsb_index_fu_398_p2 = ($signed(sub_ln1145_reg_687) + $signed(32'd4294967272));

assign lshr_ln1148_fu_428_p2 = 24'd16777215 >> zext_ln1148_fu_424_p1;

assign lshr_ln1159_fu_515_p2 = zext_ln1158_fu_503_p1 >> zext_ln1159_fu_511_p1;

assign m_2_fu_536_p3 = ((icmp_ln1159_reg_714[0:0] == 1'b1) ? lshr_ln1159_fu_515_p2 : shl_ln1160_fu_530_p2);

assign m_3_fu_546_p2 = (m_2_fu_536_p3 + zext_ln1162_fu_543_p1);

assign or_ln1150_fu_483_p2 = (and_ln1150_fu_477_p2 | a_fu_445_p2);

assign or_ln_fu_489_p3 = {{1'd0}, {or_ln1150_fu_483_p2}};

assign out_C_TDATA = ((icmp_ln1136_reg_675_pp0_iter5_reg[0:0] == 1'b1) ? 32'd0 : LD_fu_610_p1);

assign out_C_TKEEP = 4'd15;

assign out_C_TLAST = local_write_last_V_reg_652_pp0_iter5_reg;

assign out_C_TSTRB = 4'd0;

assign output_C_V_address0 = zext_ln1136_2_fu_322_p1;

assign p_Result_3_fu_470_p3 = tmp_V_2_reg_680[add_ln1150_fu_465_p2];

assign p_Result_4_fu_434_p2 = (tmp_V_2_reg_680 & lshr_ln1148_fu_428_p2);

assign p_Result_8_fu_360_p3 = {{1'd1}, {p_Result_s_fu_350_p4}};

assign p_Result_9_fu_598_p5 = {{zext_ln1163_fu_570_p1[63:32]}, {tmp_7_fu_591_p3}, {zext_ln1163_fu_570_p1[22:0]}};

integer ap_tvar_int_0;

always @ (tmp_V_2_fu_344_p3) begin
    for (ap_tvar_int_0 = 24 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 23 - 0) begin
            p_Result_s_fu_350_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_350_p4[ap_tvar_int_0] = tmp_V_2_fu_344_p3[23 - ap_tvar_int_0];
        end
    end
end

assign select_ln109_1_fu_225_p3 = ((icmp_ln111_fu_211_p2[0:0] == 1'b1) ? add_ln109_fu_205_p2 : ap_sig_allocacmp_row_load);

assign select_ln109_2_fu_271_p3 = ((icmp_ln111_fu_211_p2[0:0] == 1'b1) ? cmp109_mid1_fu_259_p2 : cmp109101_fu_265_p2);

assign select_ln109_fu_217_p3 = ((icmp_ln111_fu_211_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_col_load);

assign select_ln1144_fu_573_p3 = ((p_Result_5_reg_724[0:0] == 1'b1) ? 8'd127 : 8'd126);

assign sext_ln1244_fu_368_p1 = $signed(p_Result_8_fu_360_p3);

assign shl_ln1160_fu_530_p2 = zext_ln1158_fu_503_p1 << zext_ln1160_fu_526_p1;

assign sub_ln1145_fu_380_p2 = (32'd24 - l_fu_372_p3);

assign sub_ln1148_fu_419_p2 = ($signed(5'd17) - $signed(trunc_ln1148_reg_699));

assign sub_ln1160_fu_521_p2 = (32'd25 - sub_ln1145_reg_687_pp0_iter4_reg);

assign sub_ln1165_fu_580_p2 = (8'd11 - trunc_ln1144_reg_704_pp0_iter5_reg);

assign tmp_1_fu_241_p3 = {{select_ln109_1_fu_225_p3}, {2'd0}};

assign tmp_2_fu_451_p3 = lsb_index_fu_398_p2[32'd31];

assign tmp_7_fu_591_p3 = {{p_Result_7_reg_669_pp0_iter5_reg}, {add_ln1170_fu_585_p2}};

assign tmp_V_2_fu_344_p3 = ((p_Result_7_reg_669[0:0] == 1'b1) ? tmp_V_fu_339_p2 : p_Val2_s_reg_662);

assign tmp_V_fu_339_p2 = (24'd0 - p_Val2_s_reg_662);

assign tmp_fu_403_p4 = {{lsb_index_fu_398_p2[31:1]}};

assign tmp_s_fu_233_p3 = {{select_ln109_1_fu_225_p3}, {4'd0}};

assign trunc_ln1144_fu_394_p1 = l_fu_372_p3[7:0];

assign trunc_ln1145_fu_386_p1 = sub_ln1145_fu_380_p2[23:0];

assign trunc_ln1148_fu_390_p1 = sub_ln1145_fu_380_p2[4:0];

assign xor_ln1150_fu_459_p2 = (tmp_2_fu_451_p3 ^ 1'd1);

assign zext_ln1136_1_fu_279_p1 = select_ln109_fu_217_p3;

assign zext_ln1136_2_fu_322_p1 = add_ln1136_1_reg_647;

assign zext_ln1136_fu_249_p1 = tmp_1_fu_241_p3;

assign zext_ln1148_fu_424_p1 = sub_ln1148_fu_419_p2;

assign zext_ln1158_fu_503_p1 = tmp_V_2_reg_680_pp0_iter4_reg;

assign zext_ln1159_fu_511_p1 = add_ln1159_fu_506_p2;

assign zext_ln1160_fu_526_p1 = sub_ln1160_fu_521_p2;

assign zext_ln1162_fu_543_p1 = or_ln_reg_709;

assign zext_ln1163_fu_570_p1 = m_4_reg_719;

always @ (posedge ap_clk) begin
    or_ln_reg_709[1] <= 1'b0;
end

endmodule //matrixmul_FXP_matrixmul_FXP_Pipeline_WC_L1_WC_L2
