// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrixmul_FXP_matrixmul_FXP_Pipeline_RB_L1_RB_L2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_AB_TVALID,
        input_B_V_address0,
        input_B_V_ce0,
        input_B_V_we0,
        input_B_V_d0,
        in_AB_TDATA,
        in_AB_TREADY,
        in_AB_TKEEP,
        in_AB_TSTRB,
        in_AB_TLAST,
        grp_fu_108_p_din0,
        grp_fu_108_p_dout0,
        grp_fu_108_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_AB_TVALID;
output  [8:0] input_B_V_address0;
output   input_B_V_ce0;
output   input_B_V_we0;
output  [23:0] input_B_V_d0;
input  [31:0] in_AB_TDATA;
output   in_AB_TREADY;
input  [3:0] in_AB_TKEEP;
input  [3:0] in_AB_TSTRB;
input  [0:0] in_AB_TLAST;
output  [31:0] grp_fu_108_p_din0;
input  [63:0] grp_fu_108_p_dout0;
output   grp_fu_108_p_ce;

reg ap_idle;
reg input_B_V_ce0;
reg input_B_V_we0;
reg in_AB_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln87_fu_156_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_AB_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_0_reg_513;
reg   [31:0] p_0_reg_513_pp0_iter1_reg;
reg   [31:0] p_0_reg_513_pp0_iter2_reg;
reg   [31:0] p_0_reg_513_pp0_iter3_reg;
wire   [31:0] tmp_4_fu_172_p1;
reg   [0:0] p_Result_s_reg_523;
reg   [10:0] exp_tmp_reg_528;
wire   [51:0] trunc_ln600_fu_208_p1;
reg   [51:0] trunc_ln600_reg_533;
wire   [0:0] icmp_ln606_fu_212_p2;
reg   [0:0] icmp_ln606_reg_538;
reg   [0:0] icmp_ln606_reg_538_pp0_iter2_reg;
reg   [0:0] icmp_ln606_reg_538_pp0_iter3_reg;
wire   [53:0] man_V_2_fu_238_p3;
reg   [53:0] man_V_2_reg_545;
reg   [53:0] man_V_2_reg_545_pp0_iter3_reg;
wire  signed [11:0] sh_amt_fu_269_p3;
reg  signed [11:0] sh_amt_reg_550;
wire   [0:0] icmp_ln617_fu_277_p2;
reg   [0:0] icmp_ln617_reg_557;
wire   [23:0] trunc_ln618_fu_283_p1;
reg   [23:0] trunc_ln618_reg_562;
wire   [0:0] and_ln616_fu_298_p2;
reg   [0:0] and_ln616_reg_568;
reg   [0:0] and_ln616_reg_568_pp0_iter3_reg;
wire  signed [31:0] sext_ln616_fu_304_p1;
reg  signed [31:0] sext_ln616_reg_573;
wire   [0:0] icmp_ln620_fu_307_p2;
reg   [0:0] icmp_ln620_reg_578;
wire   [23:0] select_ln617_fu_344_p3;
reg   [23:0] select_ln617_reg_583;
wire   [8:0] add_ln92_1_fu_415_p2;
reg   [8:0] add_ln92_1_reg_588;
wire   [23:0] select_ln606_fu_461_p3;
reg   [23:0] select_ln606_reg_593;
wire   [63:0] zext_ln92_2_fu_484_p1;
reg   [4:0] col_fu_98;
wire   [4:0] add_ln89_fu_468_p2;
wire    ap_loop_init;
reg   [4:0] row_fu_102;
wire   [4:0] select_ln87_1_fu_377_p3;
reg   [8:0] indvar_flatten6_fu_106;
wire   [8:0] add_ln87_1_fu_162_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [63:0] ireg_fu_182_p1;
wire   [62:0] trunc_ln590_fu_186_p1;
wire   [52:0] p_Result_10_fu_221_p3;
wire   [53:0] zext_ln604_fu_228_p1;
wire   [53:0] man_V_1_fu_232_p2;
wire   [11:0] zext_ln501_fu_218_p1;
wire   [11:0] F2_fu_245_p2;
wire   [0:0] icmp_ln616_fu_251_p2;
wire   [11:0] add_ln616_fu_257_p2;
wire   [11:0] sub_ln616_fu_263_p2;
wire   [0:0] or_ln617_fu_287_p2;
wire   [0:0] xor_ln617_fu_292_p2;
wire   [23:0] sext_ln616cast_fu_317_p1;
wire   [0:0] icmp_ln638_fu_312_p2;
wire   [23:0] shl_ln639_fu_321_p2;
wire   [0:0] xor_ln606_fu_334_p2;
wire   [0:0] and_ln617_fu_339_p2;
wire   [23:0] select_ln638_fu_326_p3;
wire   [0:0] icmp_ln89_fu_363_p2;
wire   [4:0] add_ln87_fu_357_p2;
wire   [6:0] tmp_8_fu_393_p3;
wire   [8:0] tmp_6_fu_385_p3;
wire   [8:0] zext_ln92_fu_401_p1;
wire   [4:0] select_ln87_fu_369_p3;
wire   [8:0] add_ln92_fu_405_p2;
wire   [8:0] zext_ln92_1_fu_411_p1;
wire   [53:0] zext_ln621_fu_421_p1;
wire   [53:0] ashr_ln621_fu_424_p2;
wire   [0:0] tmp_fu_433_p3;
wire   [23:0] trunc_ln621_fu_429_p1;
wire   [23:0] select_ln623_fu_440_p3;
wire   [23:0] select_ln620_fu_448_p3;
wire   [23:0] select_ln616_fu_455_p3;
reg    grp_fu_135_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixmul_FXP_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            col_fu_98 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            col_fu_98 <= add_ln89_fu_468_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_156_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            indvar_flatten6_fu_106 <= add_ln87_1_fu_162_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_106 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            row_fu_102 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            row_fu_102 <= select_ln87_1_fu_377_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln92_1_reg_588 <= add_ln92_1_fu_415_p2;
        and_ln616_reg_568_pp0_iter3_reg <= and_ln616_reg_568;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln606_reg_538_pp0_iter2_reg <= icmp_ln606_reg_538;
        icmp_ln606_reg_538_pp0_iter3_reg <= icmp_ln606_reg_538_pp0_iter2_reg;
        man_V_2_reg_545_pp0_iter3_reg <= man_V_2_reg_545;
        p_0_reg_513_pp0_iter2_reg <= p_0_reg_513_pp0_iter1_reg;
        p_0_reg_513_pp0_iter3_reg <= p_0_reg_513_pp0_iter2_reg;
        select_ln606_reg_593 <= select_ln606_fu_461_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_538 == 1'd0))) begin
        and_ln616_reg_568 <= and_ln616_fu_298_p2;
        icmp_ln617_reg_557 <= icmp_ln617_fu_277_p2;
        man_V_2_reg_545 <= man_V_2_fu_238_p3;
        sh_amt_reg_550 <= sh_amt_fu_269_p3;
        trunc_ln618_reg_562 <= trunc_ln618_fu_283_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        exp_tmp_reg_528 <= {{ireg_fu_182_p1[62:52]}};
        icmp_ln606_reg_538 <= icmp_ln606_fu_212_p2;
        p_0_reg_513_pp0_iter1_reg <= p_0_reg_513;
        p_Result_s_reg_523 <= ireg_fu_182_p1[32'd63];
        trunc_ln600_reg_533 <= trunc_ln600_fu_208_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln616_reg_568) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_538_pp0_iter2_reg == 1'd0))) begin
        icmp_ln620_reg_578 <= icmp_ln620_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln87_fu_156_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_reg_513 <= in_AB_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln616_reg_568) & (icmp_ln606_reg_538_pp0_iter2_reg == 1'd0))) begin
        select_ln617_reg_583 <= select_ln617_fu_344_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln606_reg_538_pp0_iter2_reg == 1'd0))) begin
        sext_ln616_reg_573 <= sext_ln616_fu_304_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln87_fu_156_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_135_ce = 1'b1;
    end else begin
        grp_fu_135_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln87_fu_156_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_AB_TDATA_blk_n = in_AB_TVALID;
    end else begin
        in_AB_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln87_fu_156_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_AB_TREADY = 1'b1;
    end else begin
        in_AB_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        input_B_V_ce0 = 1'b1;
    end else begin
        input_B_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        input_B_V_we0 = 1'b1;
    end else begin
        input_B_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_245_p2 = (12'd1075 - zext_ln501_fu_218_p1);

assign add_ln616_fu_257_p2 = ($signed(F2_fu_245_p2) + $signed(12'd4083));

assign add_ln87_1_fu_162_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 9'd1);

assign add_ln87_fu_357_p2 = (row_fu_102 + 5'd1);

assign add_ln89_fu_468_p2 = (select_ln87_fu_369_p3 + 5'd1);

assign add_ln92_1_fu_415_p2 = (add_ln92_fu_405_p2 + zext_ln92_1_fu_411_p1);

assign add_ln92_fu_405_p2 = (tmp_6_fu_385_p3 + zext_ln92_fu_401_p1);

assign and_ln616_fu_298_p2 = (xor_ln617_fu_292_p2 & icmp_ln616_fu_251_p2);

assign and_ln617_fu_339_p2 = (xor_ln606_fu_334_p2 & icmp_ln617_reg_557);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln87_fu_156_p2 == 1'd0) & (in_AB_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln87_fu_156_p2 == 1'd0) & (in_AB_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln87_fu_156_p2 == 1'd0) & (in_AB_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ashr_ln621_fu_424_p2 = $signed(man_V_2_reg_545_pp0_iter3_reg) >>> zext_ln621_fu_421_p1;

assign grp_fu_108_p_ce = grp_fu_135_ce;

assign grp_fu_108_p_din0 = tmp_4_fu_172_p1;

assign icmp_ln606_fu_212_p2 = ((trunc_ln590_fu_186_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln616_fu_251_p2 = (($signed(F2_fu_245_p2) > $signed(12'd13)) ? 1'b1 : 1'b0);

assign icmp_ln617_fu_277_p2 = ((F2_fu_245_p2 == 12'd13) ? 1'b1 : 1'b0);

assign icmp_ln620_fu_307_p2 = ((sh_amt_reg_550 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln638_fu_312_p2 = ((sh_amt_reg_550 < 12'd24) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_156_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 9'd400) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_363_p2 = ((col_fu_98 == 5'd20) ? 1'b1 : 1'b0);

assign input_B_V_address0 = zext_ln92_2_fu_484_p1;

assign input_B_V_d0 = select_ln606_reg_593;

assign ireg_fu_182_p1 = grp_fu_108_p_dout0;

assign man_V_1_fu_232_p2 = (54'd0 - zext_ln604_fu_228_p1);

assign man_V_2_fu_238_p3 = ((p_Result_s_reg_523[0:0] == 1'b1) ? man_V_1_fu_232_p2 : zext_ln604_fu_228_p1);

assign or_ln617_fu_287_p2 = (icmp_ln617_fu_277_p2 | icmp_ln606_reg_538);

assign p_Result_10_fu_221_p3 = {{1'd1}, {trunc_ln600_reg_533}};

assign select_ln606_fu_461_p3 = ((icmp_ln606_reg_538_pp0_iter3_reg[0:0] == 1'b1) ? 24'd0 : select_ln616_fu_455_p3);

assign select_ln616_fu_455_p3 = ((and_ln616_reg_568_pp0_iter3_reg[0:0] == 1'b1) ? select_ln620_fu_448_p3 : select_ln617_reg_583);

assign select_ln617_fu_344_p3 = ((and_ln617_fu_339_p2[0:0] == 1'b1) ? trunc_ln618_reg_562 : select_ln638_fu_326_p3);

assign select_ln620_fu_448_p3 = ((icmp_ln620_reg_578[0:0] == 1'b1) ? trunc_ln621_fu_429_p1 : select_ln623_fu_440_p3);

assign select_ln623_fu_440_p3 = ((tmp_fu_433_p3[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln638_fu_326_p3 = ((icmp_ln638_fu_312_p2[0:0] == 1'b1) ? shl_ln639_fu_321_p2 : 24'd0);

assign select_ln87_1_fu_377_p3 = ((icmp_ln89_fu_363_p2[0:0] == 1'b1) ? add_ln87_fu_357_p2 : row_fu_102);

assign select_ln87_fu_369_p3 = ((icmp_ln89_fu_363_p2[0:0] == 1'b1) ? 5'd0 : col_fu_98);

assign sext_ln616_fu_304_p1 = sh_amt_reg_550;

assign sext_ln616cast_fu_317_p1 = sext_ln616_fu_304_p1[23:0];

assign sh_amt_fu_269_p3 = ((icmp_ln616_fu_251_p2[0:0] == 1'b1) ? add_ln616_fu_257_p2 : sub_ln616_fu_263_p2);

assign shl_ln639_fu_321_p2 = trunc_ln618_reg_562 << sext_ln616cast_fu_317_p1;

assign sub_ln616_fu_263_p2 = (12'd13 - F2_fu_245_p2);

assign tmp_4_fu_172_p1 = in_AB_TDATA;

assign tmp_6_fu_385_p3 = {{select_ln87_1_fu_377_p3}, {4'd0}};

assign tmp_8_fu_393_p3 = {{select_ln87_1_fu_377_p3}, {2'd0}};

assign tmp_fu_433_p3 = p_0_reg_513_pp0_iter3_reg[32'd31];

assign trunc_ln590_fu_186_p1 = ireg_fu_182_p1[62:0];

assign trunc_ln600_fu_208_p1 = ireg_fu_182_p1[51:0];

assign trunc_ln618_fu_283_p1 = man_V_2_fu_238_p3[23:0];

assign trunc_ln621_fu_429_p1 = ashr_ln621_fu_424_p2[23:0];

assign xor_ln606_fu_334_p2 = (icmp_ln606_reg_538_pp0_iter2_reg ^ 1'd1);

assign xor_ln617_fu_292_p2 = (or_ln617_fu_287_p2 ^ 1'd1);

assign zext_ln501_fu_218_p1 = exp_tmp_reg_528;

assign zext_ln604_fu_228_p1 = p_Result_10_fu_221_p3;

assign zext_ln621_fu_421_p1 = $unsigned(sext_ln616_reg_573);

assign zext_ln92_1_fu_411_p1 = select_ln87_fu_369_p3;

assign zext_ln92_2_fu_484_p1 = add_ln92_1_reg_588;

assign zext_ln92_fu_401_p1 = tmp_8_fu_393_p3;

endmodule //matrixmul_FXP_matrixmul_FXP_Pipeline_RB_L1_RB_L2
