// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cm_top_cm_top_Pipeline_VITIS_LOOP_15_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        input_M_value_address0,
        input_M_value_ce0,
        input_M_value_we0,
        input_M_value_d0,
        input_M_value_1_address0,
        input_M_value_1_ce0,
        input_M_value_1_we0,
        input_M_value_1_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [63:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [7:0] in_stream_TKEEP;
input  [7:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [8:0] input_M_value_address0;
output   input_M_value_ce0;
output   input_M_value_we0;
output  [31:0] input_M_value_d0;
output  [8:0] input_M_value_1_address0;
output   input_M_value_1_ce0;
output   input_M_value_1_we0;
output  [31:0] input_M_value_1_d0;

reg ap_idle;
reg in_stream_TREADY;
reg input_M_value_ce0;
reg input_M_value_we0;
reg input_M_value_1_ce0;
reg input_M_value_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln15_fu_104_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire   [63:0] i_cast_fu_116_p1;
reg   [9:0] i_fu_54;
wire   [9:0] add_ln15_fu_110_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_2;
wire   [31:0] trunc_ln293_fu_126_p1;
wire   [31:0] trunc_ln293_1_fu_135_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_133;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

cm_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_133)) begin
        if ((icmp_ln15_fu_104_p2 == 1'd0)) begin
            i_fu_54 <= add_ln15_fu_110_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 10'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_104_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_54;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input_M_value_1_ce0 = 1'b1;
    end else begin
        input_M_value_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_M_value_1_we0 = 1'b1;
    end else begin
        input_M_value_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        input_M_value_ce0 = 1'b1;
    end else begin
        input_M_value_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input_M_value_we0 = 1'b1;
    end else begin
        input_M_value_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_110_p2 = (ap_sig_allocacmp_i_2 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_133 = (~((ap_start_int == 1'b0) | ((icmp_ln15_fu_104_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_cast_fu_116_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln15_fu_104_p2 = ((ap_sig_allocacmp_i_2 == 10'd512) ? 1'b1 : 1'b0);

assign input_M_value_1_address0 = i_cast_fu_116_p1;

assign input_M_value_1_d0 = trunc_ln293_1_fu_135_p4;

assign input_M_value_address0 = i_cast_fu_116_p1;

assign input_M_value_d0 = trunc_ln293_fu_126_p1;

assign trunc_ln293_1_fu_135_p4 = {{in_stream_TDATA[63:32]}};

assign trunc_ln293_fu_126_p1 = in_stream_TDATA[31:0];

endmodule //cm_top_cm_top_Pipeline_VITIS_LOOP_15_1
